# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet Side by Side testing sample
    steps:
    - uses: actions/checkout@v2
    - run: dotnet restore; dotnet build --configuration Release --no-restore
    - name: create config from env
      run: cd test; dotnet run genenv.cs; cat config.xml;
      env:
        MY_ENV: ${{ secrets.MY_ENV }}

